// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./.vitepress/theme/components/Checkbox.vue')['default']
    CurrencyInput: typeof import('./.vitepress/theme/components/CurrencyInput.vue')['default']
    Demo: typeof import('./.vitepress/theme/components/Demo.vue')['default']
    Dialog: typeof import('./.vitepress/theme/components/Dialog.vue')['default']
    Embed: typeof import('./.vitepress/theme/components/Embed.vue')['default']
    OptionSection: typeof import('./.vitepress/theme/components/OptionSection.vue')['default']
    Switch: typeof import('./.vitepress/theme/components/Switch.vue')['default']
  }
}

export {}
