name: Release
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v5
        if: ${{ steps.release.outputs.release_created }}
      - uses: pnpm/action-setup@v6
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm install
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm build
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish --provenance --tag latest
        if: ${{ steps.release.outputs.release_created }}
